[project]
name = "airflow-hw-v3"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9,<3.13"
dependencies = [
    "apache-airflow>=2.10.5",
    "dill>=0.3.9",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
